MODEL:
  # WEIGHT: "catalog://ImageNetPretrained/DLA34"
  WEIGHT: "./SMOKE/pre_trained/model_final.pth"
INPUT:
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
DATASETS:
  DETECT_CLASSES: ("Car", "Cyclist", "Pedestrian")
  TRAIN: ("kitti_train",)
  TEST: ("kitti_test",)
  TRAIN_SPLIT: "trainval"
  TEST_SPLIT: "val"
SOLVER:
  BASE_LR: 2.5e-4
  STEPS: (2000, 4000, 6000)
  MAX_ITERATION: 10000
  IMS_PER_BATCH: 8